"""add_false_positive_fields_to_alerts

Revision ID: 311a544d848f
Revises: 2026_07_08_00
Create Date: 2026-07-11 11:23:08.863234+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by alembic.
revision: str = '311a544d848f'
down_revision: str | None = '2026_07_08_00'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('false_positive', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('fp_category', sa.String(length=50), nullable=True))
    op.create_index('ix_alerts_false_positive', 'alerts', ['false_positive'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_false_positive', table_name='alerts')
    op.drop_column('alerts', 'fp_category')
    op.drop_column('alerts', 'false_positive')
    # ### end Alembic commands ###

